# Generated by Django 5.0.2 on 2024-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_UserEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=30)),
                ('Purpose', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Admin User Enquiry',
            },
        ),
    ]
