# Generated by Django 5.0.2 on 2024-02-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Mobile', models.CharField(max_length=30, null=True)),
                ('Email', models.CharField(max_length=30, null=True)),
                ('Password', models.CharField(max_length=30, null=True)),
                ('Status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_image', models.ImageField(upload_to='imagess/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userr.user')),
            ],
            options={
                'db_table': 'image_user',
            },
        ),
    ]
