# Generated by Django 5.0.2 on 2024-02-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=20, null=True)),
                ('Phone_number', models.CharField(max_length=20, null=True)),
                ('Qualification', models.CharField(max_length=30, null=True)),
                ('Experience', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(null=True, upload_to='imagess')),
                ('Password', models.CharField(max_length=30, null=True)),
                ('Create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(default='Pending', max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineers.category')),
            ],
            options={
                'db_table': 'Engineer',
            },
        ),
        migrations.CreateModel(
            name='Engineer_contact_enquiryy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('eng', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineers.engineer')),
            ],
            options={
                'db_table': 'engineer_contact_enquiry2',
            },
        ),
        migrations.CreateModel(
            name='Engineerproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField(auto_created=True)),
                ('Project_Title', models.CharField(max_length=80, null=True)),
                ('Project_description', models.CharField(max_length=300, null=True)),
                ('Place', models.CharField(max_length=300, null=True)),
                ('End_Date', models.DateField()),
                ('Contact_number', models.CharField(max_length=40, null=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineers.engineer')),
            ],
            options={
                'db_table': 'Engineer_Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectImg', models.ImageField(null=True, upload_to='imagess/')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineers.engineerproject')),
            ],
            options={
                'db_table': 'ProjectImages',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.CharField(max_length=300)),
                ('Rating', models.CharField(max_length=20)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineers.engineerproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userr.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineers.engineerproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userr.user')),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
    ]
